name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Check if domains are sorted alphabetically
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check domain sorting
        run: |
          sh scripts/check_alphabetical_sorting.sh